channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip==21.3.1
  - numpy==1.22.0
  - ipykernel==6.6.1
  - plotly==5.5.0
  - nbformat==5.1.3
  - pandas==1.3.5
  - click==8.0.3
  - pip:
    - -e .

